### ISSUE TITLE
Channel

### ISSUE THREAD

**Issue by KSOWNDAR** [mithun30052001/Discussion-Forum#10]
After sign up as admit I clicked Create Channel
I doesn't give any channel name and click "CREATE"
It should not be created.But it is created
![Screenshot (49)](https://user-images.githubusercontent.com/84360457/198254282-70db1a0f-04c1-408d-97bf-780674067afb.png)
![Screenshot (50)](https://user-images.githubusercontent.com/84360457/198254301-52f3d79d-9f41-4314-a0d4-64c7f3edf20c.png)

**Comment by tusharravindran** [comment]
Issue Solved 
**Before**
![image](https://user-images.githubusercontent.com/57782379/198588781-fe3c2926-29de-4724-a0ff-1a48fcec05ef.png)
**After**
![image](https://user-images.githubusercontent.com/57782379/198588929-719fe54d-5235-4945-b2e1-be208ef19332.png)
