### ISSUE TITLE
Duplicate channels

### ISSUE THREAD

**Issue by KSOWNDAR** [mithun30052001/Discussion-Forum#11]
- In create channel form, If I give the name of the channel which is already exists it should show already exists, but it is created.
- Duplicate channels are creating, which leads to confusion for both admin and user under which channel the particular discussion is created
![Screenshot (52)](https://user-images.githubusercontent.com/84360457/198256009-46e97280-17e3-4482-a5fb-8539588b0d18.png)

**Comment by tusharravindran** [comment]
Completed Solving Issue
