### ISSUE TITLE
By using URL non admin users can also edit or delete discussion and channel

### ISSUE THREAD

**Issue by vasanthakumar-a** [mithun30052001/Discussion-Forum#13]
- Go to the localhost:3000
- By using admin login create channel and discussion<br>
- Now logout and login as user go to URL and type
 `http://127.0.0.1:3000/channels/[channel_name]/edit`
 `http://127.0.0.1:3000/discussions/[discussion_name]/edit`<br>
- Now user can edit the channel or discussion<br>
![Screenshot (76)](https://user-images.githubusercontent.com/81355826/198298707-099def35-92c9-4283-802f-38d61bebb68f.png)
![Screenshot (77)](https://user-images.githubusercontent.com/81355826/198298744-90f9fd76-7e40-4d6e-976a-a8482ef9f0d2.png)
![Screenshot (78)](https://user-images.githubusercontent.com/81355826/198298764-54d243ad-cbd9-459a-9021-c4c6eebad6e9.png)

**Comment by KSOWNDAR** [comment]
Now it is fixed Vasanth
Only those who are created discussion only able to edit 
Only admin has feature to edit the channel
![Screenshot (65)](https://user-images.githubusercontent.com/84360457/198773145-fecd7bac-2c3f-49cd-bdb4-ed70235dd0a9.png)
![Screenshot (66)](https://user-images.githubusercontent.com/84360457/198773171-4f2f2077-0866-4f8d-b209-e95d7142f76d.png)

**Comment by mithun30052001** [comment]
Bug fixed
