### ISSUE TITLE
If the channel is deleted the discussions of that channel is displays empty page

### ISSUE THREAD

**Issue by vasanthakumar-a** [mithun30052001/Discussion-Forum#14]
- Go to the localhost:3000<br>
- By using the admin login create a channel and discussions for that channel
- Now in URL type 
`http://localhost:3000/channels`<br>

- Delete the channel that has discussions in it<br>

![Screenshot (82)](https://user-images.githubusercontent.com/81355826/198309944-5595f887-8373-4756-a0c7-98ce4e189891.png)
<br>

- Now go to root page, **the Discussion is listed** <br><br>

![Screenshot (83)](https://user-images.githubusercontent.com/81355826/198310135-d330c1d2-f140-4efc-9836-99c5cfc09417.png)
<br>

- Click on the Discussion, **Now it shows Empty Page** <br><br>

![Screenshot (84)](https://user-images.githubusercontent.com/81355826/198310222-4f37ac47-c3ae-4f6b-bfed-a7e12a026864.png)

**Comment by tusharravindran** [comment]
Added validation

**Comment by tusharravindran** [comment]
validations added
