### ISSUE TITLE
No Pagination for Channels which goes on and displays all the channel if has more than 1000 also

### ISSUE THREAD

**Issue by vasanthakumar-a** [mithun30052001/Discussion-Forum#15]
No Pagination for Channels which goes on and displays all the channel if has more than 1000 also

- By using faker generate 1000 channels

> In seed.rb

```
Channel.destroy_all

1000.times do |i|
  Channel.create(channel: "haha")
end
```

> In console

`$ rails db:seed
`
- Now go to "localhost:3000"

 
![chrome-capture-2022-9-27](https://user-images.githubusercontent.com/81355826/198366112-95901fb2-482f-4b73-8c6b-f7f6dfa3c83d.gif)

**Comment by mithun30052001** [comment]
Pagination and fakers will be added once all the errors are cleared

**Comment by tusharravindran** [comment]
added pagination
