### ISSUE TITLE
Username can be given as empty shows nothing

### ISSUE THREAD

**Issue by vasanthakumar-a** [mithun30052001/Discussion-Forum#16]
While Signup or Editing the user, the username field can be given empty

![Screenshot (85)](https://user-images.githubusercontent.com/81355826/198367673-4df70438-e7ab-4a5e-adbf-e1c497437645.png)

It shows nothing on the Root page so we can't find the created of the specific discussion

![Screenshot (86)](https://user-images.githubusercontent.com/81355826/198367871-fb9998fd-ece8-490e-b2da-e501cc81e880.png)

You can see `Posted 10 minutes ago in by`<br>
There username is empty so we can't find the creator of that discussion

**Comment by KSOWNDAR** [comment]
Now this bug is solved vasanth.
I added a validation for username.
![Screenshot (64)](https://user-images.githubusercontent.com/84360457/198759937-859ce187-9d1e-4867-b0bb-5de454e3814c.png)

**Comment by mithun30052001** [comment]
Bug is fixed
