### ISSUE TITLE
Pdf

### ISSUE THREAD

**Issue by KSOWNDAR** [mithun30052001/Discussion-Forum#7]
- I created a account and update role as admin for User name: sowndar
- In that account I posted a discussion named DEMO with a pdf.
- When I try to view the contents in discussion only the name of file visible ,option to view or download pdf is not visible.

**Comment by tusharravindran** [comment]
Issue Solved 

**before**
![1](https://user-images.githubusercontent.com/57782379/198589066-0f43a04f-aaa1-4b4e-a9c0-93a3fb113b7a.jpg)
**after
![2](https://user-images.githubusercontent.com/57782379/198589085-d641ccfc-fe83-48f9-817b-25da6b92ab16.jpg)
