### ISSUE TITLE
New dicussion form

### ISSUE THREAD

**Issue by KSOWNDAR** [mithun30052001/Discussion-Forum#9]
- After sign up and make the user as admin,I tried to create a new discussion
- If I give the content in new discussion form as empty, it has to show warnings or where the error is came Instead of that it directed me to error page where I can't find what's the problem.
![Screenshot (47)](https://user-images.githubusercontent.com/84360457/198252425-6dbef6d7-0e14-4880-91e2-b9f92b61eda2.png)
![Screenshot (48)](https://user-images.githubusercontent.com/84360457/198252437-c025c87d-6006-4934-9c08-0b413ecc659b.png)

**Comment by tusharravindran** [comment]
Issue solved with validations
![image](https://user-images.githubusercontent.com/57782379/198866199-3eedf2bc-2e7a-4a4a-b061-c6455de35df5.png)
